//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager.Core.Mock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostNordResponseData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostNordResponseData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManager.Core.Mock.PostNordResponseData", typeof(PostNordResponseData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TrackingInformationResponse&quot;: {
        ///    &quot;shipments&quot;: [
        ///      {
        ///        &quot;shipmentId&quot;: &quot;00073942910063717801&quot;,
        ///        &quot;assessedNumberOfItems&quot;: 1,
        ///        &quot;deliveryDate&quot;: &quot;2018-04-25T14:27:00&quot;,
        ///        &quot;service&quot;: {
        ///          &quot;code&quot;: &quot;19&quot;,
        ///          &quot;name&quot;: &quot;PostNord MyPack Collect&quot;
        ///        },
        ///        &quot;consignor&quot;: {
        ///          &quot;name&quot;: &quot;NetOnNet&quot;,
        ///          &quot;address&quot;: {
        ///            &quot;street1&quot;: &quot;Företagsgatan 69&quot;,
        ///            &quot;city&quot;: &quot;BORÅS&quot;,
        ///            &quot;countryCode&quot;: &quot;SWE&quot;,
        ///            &quot;country [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostNordResponseMock {
            get {
                return ResourceManager.GetString("PostNordResponseMock", resourceCulture);
            }
        }
    }
}
