//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int Id { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentSenderPersonId { get; set; }
        public string PaymentReceiverPersonId { get; set; }
        public int InvitationId { get; set; }
        public int DepositAmount { get; set; }
        public int PaymentMethod { get; set; }
        public string TransactionId { get; set; }
    }
}
